services:
  api:
    build:
      target: production

    environment:
      NODE_ENV: production

    ports:
      - "127.0.0.1:3001:3001"


  web:
    build:
      target: production

    environment:
      NODE_ENV: production

    ports:
      - "127.0.0.1:3000:3000"
  postgres:
    ports:
      - "127.0.0.1:5432:5432"