"use client";
import Link from "next/link";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAdminSession } from "../admin-session";
import "./inventory.css";

type Location={id:string;name:string;isDefault:boolean;isActive:boolean};
type Category={id:string;name:string;isActive:boolean};
type Stock={itemId:string;name:string;sku:string|null;dimension:string;baseUnit:string;isActive:boolean;categoryName:string|null;locationId:string;locationName:string;quantityBase:string;averageUnitCostToman:string|null;lastMovementAt:string|null};
type Item={id:string;name:string;sku:string|null;description:string|null;dimension:string;baseUnit:string;categoryId:string|null;categoryName:string|null;isActive:boolean};
type Count={id:string;locationId:string;locationName:string;status:"DRAFT"|"COMPLETED";note:string|null;createdAt:string;completedAt:string|null;lineCount:number;lines?:Array<{itemId:string;itemName:string;baseUnit:string;expectedQuantity:string;countedQuantity:string;varianceQuantity:string|null}>};
type Movement={id:string;itemName:string;locationName:string;type:string;quantityBase:string;unitCostToman:string|null;totalCostToman:string|null;reason:string|null;actorUserId:string|null;createdAt:string};
type Page<T>={items:T[];page:number;limit:number;total:number};
type Overview={activeItems:number;negativeBalances:number;draftCounts:number;recentAdjustments:number};
type Tab="overview"|"items"|"counts"|"history"|"locations";
const fa=(value:string|number)=>new Intl.NumberFormat("fa-IR").format(Number(value));
const decimal=(v:string)=>v.replace(/\B(?=(\d{3})+(?!\d))/g,"٬").replace(/\./g,"٫").replace(/\d/g,d=>"۰۱۲۳۴۵۶۷۸۹"[Number(d)]!);
const movementNames:Record<string,string>={OPENING_BALANCE:"موجودی اولیه",PURCHASE_RECEIPT:"دریافت خرید",MANUAL_ADJUSTMENT:"اصلاح موجودی",STOCK_COUNT_ADJUSTMENT:"اصلاح انبارگردانی",SALE_CONSUMPTION:"مصرف سفارش",SALE_REVERSAL:"بازگشت موجودی سفارش"};
const unitNames:Record<string,string>={g:"گرم",kg:"کیلوگرم",ml:"میلی‌لیتر",l:"لیتر",piece:"عدد",pack:"بسته",box:"جعبه",bottle:"بطری"};

export default function InventoryPage(){
  const {access,api}=useAdminSession();
  const [tab,setTab]=useState<Tab>("overview"); const [stock,setStock]=useState<Page<Stock>>({items:[],page:1,limit:100,total:0}); const [items,setItems]=useState<Item[]>([]); const [locations,setLocations]=useState<Location[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [counts,setCounts]=useState<Page<Count>>({items:[],page:1,limit:30,total:0}); const [stockPage,setStockPage]=useState(1); const [countPage,setCountPage]=useState(1); const [movementPage,setMovementPage]=useState(1); const [movements,setMovements]=useState<Page<Movement>>({items:[],page:1,limit:30,total:0});
  const [overview,setOverview]=useState<Overview>({activeItems:0,negativeBalances:0,draftCounts:0,recentAdjustments:0});const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [search,setSearch]=useState("");const [locationFilter,setLocationFilter]=useState("");const [categoryFilter,setCategoryFilter]=useState("");const [activeFilter,setActiveFilter]=useState("true");const [movementItem,setMovementItem]=useState("");const [movementLocation,setMovementLocation]=useState("");const [movementType,setMovementType]=useState("");const [selectedCount,setSelectedCount]=useState("");const [countDetail,setCountDetail]=useState<Count|null>(null);const [countValues,setCountValues]=useState<Record<string,string>>({});const [adjusting,setAdjusting]=useState<string>("");const [editingItem,setEditingItem]=useState<Item|null>(null);
  const [refresh,setRefresh]=useState(-1);
  const canRead=access.permissions.includes("inventory.read")||access.permissions.includes("inventory.manage");const canManage=access.permissions.includes("inventory.manage");
  const load=useCallback(async()=>{if(access.features?.inventory===false||!canRead)return;setBusy(true);setError("");try{const [firstItems,l,c,o]=await Promise.all([api<Page<Item>>(`/tenant/inventory/items?limit=100&page=1`),api<Location[]>("/tenant/inventory/locations"),api<Category[]>("/tenant/inventory/categories"),api<Overview>("/tenant/inventory/overview")]);
    const itemPages=await Promise.all(Array.from({length:Math.ceil(firstItems.total/100)-1},(_,index)=>api<Page<Item>>(`/tenant/inventory/items?limit=100&page=${index+2}`)));
    setItems([firstItems,...itemPages].flatMap(p=>p.items));setLocations(l);setCategories(c);setOverview(o);setRefresh(value=>value+1);
  }catch(e){setError(e instanceof Error?e.message:"دریافت اطلاعات موجودی ممکن نشد.");}finally{setBusy(false);}},[access.features?.inventory,api,canRead]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(refresh<0||access.features?.inventory===false||!canRead)return;let canceled=false;const timer=setTimeout(()=>{void api<Page<Stock>>(`/tenant/inventory/stock?limit=100&page=${stockPage}&active=${activeFilter}${search?`&search=${encodeURIComponent(search)}`:""}${locationFilter?`&locationId=${locationFilter}`:""}${categoryFilter?`&categoryId=${categoryFilter}`:""}`).then(result=>{if(!canceled)setStock(result);}).catch(e=>{if(!canceled)setError(e.message);});},search?250:0);return()=>{canceled=true;clearTimeout(timer);};},[api,access.features?.inventory,canRead,refresh,stockPage,activeFilter,search,locationFilter,categoryFilter]);
  useEffect(()=>{if(refresh<0||access.features?.inventory===false||!canRead)return;let canceled=false;const query=new URLSearchParams({limit:"30",page:String(movementPage)});if(movementItem)query.set("itemId",movementItem);if(movementLocation)query.set("locationId",movementLocation);if(movementType)query.set("type",movementType);void api<Page<Movement>>(`/tenant/inventory/movements?${query}`).then(result=>{if(!canceled)setMovements(result);}).catch(e=>{if(!canceled)setError(e.message);});return()=>{canceled=true;};},[api,access.features?.inventory,canRead,refresh,movementPage,movementItem,movementLocation,movementType]);
  useEffect(()=>{if(refresh<0||access.features?.inventory===false||!canRead)return;let canceled=false;void api<Page<Count>>(`/tenant/inventory/counts?limit=30&page=${countPage}`).then(result=>{if(!canceled)setCounts(result);}).catch(e=>{if(!canceled)setError(e.message);});return()=>{canceled=true;};},[api,access.features?.inventory,canRead,refresh,countPage]);
  const flash=(text:string)=>{setNotice(text);setTimeout(()=>setNotice(""),3500);};
  const updateItem=async(e:FormEvent<HTMLFormElement>,item:Item)=>{e.preventDefault();const form=e.currentTarget;const raw=Object.fromEntries(new FormData(form).entries());const payload=Object.fromEntries(Object.entries(raw).map(([key,value])=>[key,value===""?null:value]));try{await api(`/tenant/inventory/items/${item.id}`,{method:"PATCH",body:JSON.stringify(payload)});setEditingItem(null);flash("مشخصات کالا به‌روز شد.");await load();}catch(err){setError(err instanceof Error?err.message:"ویرایش کالا انجام نشد.");}};
  const submit=async(e:FormEvent<HTMLFormElement>,path:string,method:"POST"|"PATCH",success:string)=>{e.preventDefault();const form=e.currentTarget;const entries=[...new FormData(form).entries()];const payload=Object.fromEntries(entries.map(([key,value])=>[key,value===""?null:key==="isDefault"?value==="true":value]));setBusy(true);setError("");try{await api(path,{method,body:JSON.stringify(payload)});form.reset();flash(success);await load();}catch(err){setError(err instanceof Error?err.message:"ذخیره انجام نشد.");}finally{setBusy(false);}};
  const createCount=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const result=await api<Count>("/tenant/inventory/counts",{method:"POST",body:JSON.stringify(Object.fromEntries(f.entries()))});setSelectedCount(result.id);setTab("counts");await load();await openCount(result.id);}catch(err){setError(err instanceof Error?err.message:"شروع انبارگردانی ممکن نشد.");}};
  const openCount=async(id:string)=>{setSelectedCount(id);try{const detail=await api<Count>(`/tenant/inventory/counts/${id}`);setCountDetail(detail);setCountValues(Object.fromEntries((detail.lines??[]).map(x=>[x.itemId,x.countedQuantity])));}catch(err){setError(err instanceof Error?err.message:"انبارگردانی پیدا نشد.");}};
  const saveCount=async()=>{if(!countDetail)return false;const lines=items.filter(i=>countValues[i.id]?.trim()!==undefined&&countValues[i.id]?.trim()!=="").map(i=>({itemId:i.id,countedQuantity:countValues[i.id]!}));setBusy(true);try{const detail=await api<Count>(`/tenant/inventory/counts/${countDetail.id}/lines`,{method:"PATCH",body:JSON.stringify({lines})});setCountDetail(detail);flash("پیش‌نویس انبارگردانی ذخیره شد.");await load();return true;}catch(e){setError(e instanceof Error?e.message:"ذخیره شمارش انجام نشد.");return false;}finally{setBusy(false);}};
  const completeCount=async()=>{if(!countDetail)return;setBusy(true);try{const detail=await api<Count>(`/tenant/inventory/counts/${countDetail.id}/complete`,{method:"POST"});setCountDetail(detail);flash("انبارگردانی ثبت نهایی شد.");await load();}catch(e){setError(e instanceof Error?e.message:"ثبت نهایی انجام نشد.");}finally{setBusy(false);}};
  const adjust=async(e:FormEvent<HTMLFormElement>,row:Stock)=>{e.preventDefault();const f=new FormData(e.currentTarget);const qty=String(f.get("quantity")??"");try{await api("/tenant/inventory/adjustments",{method:"POST",body:JSON.stringify({itemId:row.itemId,locationId:row.locationId,quantity:qty,reason:f.get("reason"),idempotencyKey:crypto.randomUUID()})});setAdjusting("");flash("اصلاح موجودی ثبت شد.");await load();}catch(err){setError(err instanceof Error?err.message:"اصلاح ثبت نشد.");}};
  const tabs:Array<[Tab,string]>=[["overview","نمای کلی"],["items","کالاها و موجودی"],["counts","انبارگردانی"],["history","تاریخچه"],["locations","تنظیمات"]];
  if(!canRead&&!canManage)return <section className="inventory-state"><h1>شما دسترسی به این بخش را ندارید</h1><p>نقش شما اجازه مشاهده موجودی این کافه را ندارد.</p></section>;
  if(access.features?.inventory===false)return <section className="inventory-state"><span>موجودی</span><h1>این قابلیت در طرح فعلی فعال نیست</h1><p>برای دسترسی به موجودی، وضعیت اشتراک را بررسی کنید.</p><a href="/admin/subscription">مشاهده اشتراک</a></section>;
  return <section className="inventory-page" dir="rtl">
    <header className="inventory-heading"><div><span>عملیات روزانه</span><h1>موجودی کافه</h1><p>کالاها، محل نگهداری و تغییرات موجودی را یکجا مدیریت کنید.</p></div><div className="inventory-heading-actions"><Link className="inventory-secondary" href="/admin/inventory/purchasing">خرید و تأمین‌کنندگان</Link><Link className="inventory-secondary" href="/admin/inventory/recipes">دستور مواد</Link>{canManage&&<button className="inventory-primary" onClick={()=>setTab("items")}>＋ افزودن کالا</button>}</div></header>
    <nav className="inventory-tabs" aria-label="بخش‌های موجودی">{tabs.map(([key,label])=><button key={key} type="button" aria-current={tab===key?"page":undefined} onClick={()=>{setTab(key);if(key==="overview")setStockPage(1);}}>{label}</button>)}</nav>
    {error&&<p className="inventory-alert" role="alert">{error}</p>}{notice&&<p className="inventory-notice" role="status">{notice}</p>}
    {tab==="overview"&&<><div className="inventory-metrics"><article><small>کالاهای فعال</small><strong>{fa(overview.activeItems)}</strong></article><article><small>موجودی منفی</small><strong>{fa(overview.negativeBalances)}</strong></article><article><small>انبارگردانی پیش‌نویس</small><strong>{fa(overview.draftCounts)}</strong></article><article><small>اصلاحات در ۷ روز</small><strong>{fa(overview.recentAdjustments)}</strong></article></div><StockTable rows={stock.items.slice(0,12)} onAdjust={canManage?setAdjusting:undefined}/><button className="inventory-secondary" onClick={()=>setTab("items")}>نمایش همه کالاها</button></>}
    {tab==="items"&&<div className="inventory-columns"><section className="inventory-panel"><div className="inventory-panel-head"><div><h2>موجودی فعلی</h2><p>موجودی منفی به‌عنوان هشدار عملیاتی حفظ می‌شود.</p></div></div><div className="inventory-filters"><input value={search} onChange={e=>{setSearch(e.target.value);setStockPage(1);}} placeholder="جست‌وجوی کالا" aria-label="جست‌وجوی کالا"/><select value={categoryFilter} onChange={e=>{setCategoryFilter(e.target.value);setStockPage(1);}}><option value="">همه دسته‌ها</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={locationFilter} onChange={e=>{setLocationFilter(e.target.value);setStockPage(1);}}><option value="">همه محل‌ها</option>{locations.filter(x=>x.isActive).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={activeFilter} onChange={e=>{setActiveFilter(e.target.value);setStockPage(1);}}><option value="true">کالاهای فعال</option><option value="false">کالاهای غیرفعال</option></select></div><StockTable rows={stock.items} onAdjust={canManage?setAdjusting:undefined}/><div className="inventory-actions"><button className="inventory-secondary" disabled={stockPage<=1} onClick={()=>setStockPage(stockPage-1)}>صفحه قبل</button><span>{fa(stock.page)} از {fa(Math.max(1,Math.ceil(stock.total/stock.limit)))}</span><button className="inventory-secondary" disabled={stockPage*stock.limit>=stock.total} onClick={()=>setStockPage(stockPage+1)}>صفحه بعد</button></div></section>
      {canManage&&<section className="inventory-panel"><div className="inventory-panel-head"><div><h2>افزودن کالا</h2><p>موجودی اولیه به شکل حرکت دفتر ثبت می‌شود.</p></div></div><form className="inventory-form" onSubmit={e=>void submit(e,"/tenant/inventory/items","POST","کالا افزوده شد.")}><label>نام کالا<input name="name" required maxLength={140}/></label><label>کد داخلی<input name="sku" maxLength={80}/></label><label>دسته‌بندی<select name="categoryId"><option value="">بدون دسته‌بندی</option>{categories.filter(c=>c.isActive).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>واحد پایه<select name="baseUnit" required><option value="g">گرم</option><option value="kg">کیلوگرم</option><option value="ml">میلی‌لیتر</option><option value="l">لیتر</option><option value="piece">عدد</option><option value="pack">بسته</option><option value="box">جعبه</option><option value="bottle">بطری</option></select></label><label>بُعد اندازه‌گیری<select name="dimension" required><option value="WEIGHT">وزن</option><option value="VOLUME">حجم</option><option value="COUNT">تعداد</option></select></label><label>محل نگهداری<select name="locationId">{locations.filter(x=>x.isActive).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>موجودی اولیه<input name="openingQuantity" inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,6})?" placeholder="۰"/></label><label className="inventory-wide">توضیحات<input name="description" maxLength={500}/></label><button className="inventory-primary" disabled={busy}>ذخیره کالا</button></form><div className="inventory-item-list">{items.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.categoryName||"بدون دسته‌بندی"} · {unitNames[item.baseUnit]}</small></div><span className={item.isActive?"":"muted"}>{item.isActive?"فعال":"غیرفعال"}</span>{canManage&&<button onClick={()=>setEditingItem(item)}>ویرایش</button>}{canManage&&<button onClick={()=>void api(`/tenant/inventory/items/${item.id}`,{method:"PATCH",body:JSON.stringify({isActive:!item.isActive})}).then(load).catch(e=>setError(e.message))}>{item.isActive?"غیرفعال‌سازی":"فعال‌سازی"}</button>}</article>)}</div></section>}
      {adjusting&&<AdjustmentDialog row={stock.items.find(x=>`${x.itemId}:${x.locationId}`===adjusting)!} close={()=>setAdjusting("")} save={adjust}/>} {editingItem&&<ItemEditDialog item={editingItem} categories={categories} close={()=>setEditingItem(null)} save={updateItem}/>}</div>}
    {tab==="counts"&&<div className="inventory-columns"><section className="inventory-panel"><div className="inventory-panel-head"><div><h2>انبارگردانی‌ها</h2><p>مبنای تطبیق، موجودی ثبت‌شده هنگام واردکردن شمارش هر کالا است.</p></div></div>{canManage&&<form className="inventory-inline-form" onSubmit={e=>void createCount(e)}><select name="locationId" required><option value="">انتخاب محل</option>{locations.filter(x=>x.isActive).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="note" placeholder="یادداشت (اختیاری)" maxLength={500}/><button className="inventory-primary">شروع انبارگردانی</button></form>}<div className="inventory-count-list">{counts.items.map(c=><button key={c.id} className={selectedCount===c.id?"selected":""} onClick={()=>void openCount(c.id)}><span><strong>{c.locationName}</strong><small>{new Date(c.createdAt).toLocaleDateString("fa-IR")} · {fa(c.lineCount)} کالا</small></span><b>{c.status==="DRAFT"?"پیش‌نویس":"ثبت نهایی"}</b></button>)}</div><div className="inventory-actions"><button className="inventory-secondary" disabled={countPage<=1} onClick={()=>setCountPage(countPage-1)}>صفحه قبل</button><span>{fa(counts.page)} از {fa(Math.max(1,Math.ceil(counts.total/counts.limit)))}</span><button className="inventory-secondary" disabled={countPage*counts.limit>=counts.total} onClick={()=>setCountPage(countPage+1)}>صفحه بعد</button></div></section>
      <section className="inventory-panel"><div className="inventory-panel-head"><div><h2>{countDetail?`شمارش ${countDetail.locationName}`:"ثبت مقدار فیزیکی"}</h2><p>{countDetail?.status==="COMPLETED"?"این انبارگردانی نهایی و قفل شده است.":"مقادیر را به واحد پایه وارد و پیش‌نویس را ذخیره کنید."}</p></div></div>{countDetail&&<><div className="inventory-count-lines">{items.filter(i=>i.isActive).map(i=><label key={i.id}><span><strong>{i.name}</strong><small>واحد: {unitNames[i.baseUnit]} · سامانه: {countDetail.lines?.find(x=>x.itemId===i.id)?.expectedQuantity??"—"}</small></span><input aria-label={`مقدار فیزیکی ${i.name}`} inputMode="decimal" placeholder="مقدار شمارش" disabled={countDetail.status!=="DRAFT"} value={countValues[i.id]??""} onChange={e=>setCountValues({...countValues,[i.id]:e.target.value})}/></label>)}</div>{countDetail.status==="DRAFT"&&canManage&&<div className="inventory-actions"><button className="inventory-secondary" disabled={busy} onClick={()=>void saveCount()}>ذخیره پیش‌نویس</button><button className="inventory-primary" disabled={busy||!(countDetail.lines?.length||Object.values(countValues).some(Boolean))} onClick={async()=>{if(await saveCount())await completeCount();}}>ثبت نهایی و اصلاح موجودی</button></div>}</>}</section></div>}
    {tab==="history"&&<section className="inventory-panel"><div className="inventory-panel-head"><div><h2>تاریخچه تغییرات</h2><p>آخرین تغییرات به تفکیک زمان ثبت.</p></div></div><div className="inventory-filters"><select aria-label="فیلتر کالا" value={movementItem} onChange={e=>{setMovementItem(e.target.value);setMovementPage(1);}}><option value="">همه کالاها</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select><select aria-label="فیلتر محل" value={movementLocation} onChange={e=>{setMovementLocation(e.target.value);setMovementPage(1);}}><option value="">همه محل‌ها</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select aria-label="فیلتر نوع حرکت" value={movementType} onChange={e=>{setMovementType(e.target.value);setMovementPage(1);}}><option value="">همه تغییرات</option><option value="OPENING_BALANCE">موجودی اولیه</option><option value="MANUAL_ADJUSTMENT">اصلاح موجودی</option><option value="STOCK_COUNT_ADJUSTMENT">اصلاح انبارگردانی</option></select></div><MovementTable data={movements}/><div className="inventory-actions"><button className="inventory-secondary" disabled={movementPage<=1||busy} onClick={()=>setMovementPage(movementPage-1)}>صفحه قبل</button><span>{fa(movements.page)} از {fa(Math.max(1,Math.ceil(movements.total/movements.limit)))}</span><button className="inventory-secondary" disabled={movementPage*movements.limit>=movements.total||busy} onClick={()=>setMovementPage(movementPage+1)}>صفحه بعد</button></div></section>}
    {tab==="locations"&&<div className="inventory-columns"><section className="inventory-panel"><h2>محل‌های نگهداری</h2>{canManage&&<form className="inventory-inline-form" onSubmit={e=>void submit(e,"/tenant/inventory/locations","POST","محل نگهداری افزوده شد.")}><input name="name" required placeholder="نام محل، مانند بار"/><label className="inventory-check"><input type="checkbox" name="isDefault" value="true"/> محل پیش‌فرض</label><button className="inventory-primary">افزودن</button></form>}<div className="inventory-item-list">{locations.map(l=><article key={l.id}><div><strong>{l.name}</strong><small>{l.isDefault?"پیش‌فرض · ":""}{l.isActive?"فعال":"غیرفعال"}</small></div>{canManage&&<button onClick={()=>{const name=window.prompt("نام محل نگهداری",l.name);if(name?.trim())void api(`/tenant/inventory/locations/${l.id}`,{method:"PATCH",body:JSON.stringify({name:name.trim()})}).then(load).catch(e=>setError(e.message));}}>ویرایش نام</button>}{canManage&&!l.isDefault&&<button onClick={()=>void api(`/tenant/inventory/locations/${l.id}`,{method:"PATCH",body:JSON.stringify({isDefault:true})}).then(load).catch(e=>setError(e.message))}>پیش‌فرض‌کردن</button>}{canManage&&<button disabled={l.isDefault&&l.isActive} onClick={()=>void api(`/tenant/inventory/locations/${l.id}`,{method:"PATCH",body:JSON.stringify({isActive:!l.isActive})}).then(load).catch(e=>setError(e.message))}>{l.isActive?"غیرفعال‌سازی":"فعال‌سازی"}</button>}</article>)}</div></section><section className="inventory-panel"><h2>دسته‌بندی‌ها</h2>{canManage&&<form className="inventory-inline-form" onSubmit={e=>void submit(e,"/tenant/inventory/categories","POST","دسته‌بندی افزوده شد.")}><input name="name" required maxLength={80} placeholder="نام دسته‌بندی"/><button className="inventory-primary">افزودن دسته</button></form>}<div className="inventory-item-list">{categories.map(c=><article key={c.id}><div><strong>{c.name}</strong><small>{c.isActive?"فعال":"غیرفعال"}</small></div>{canManage&&<button onClick={()=>{const name=window.prompt("نام دسته‌بندی",c.name);if(name?.trim())void api(`/tenant/inventory/categories/${c.id}`,{method:"PATCH",body:JSON.stringify({name:name.trim()})}).then(load).catch(e=>setError(e.message));}}>ویرایش نام</button>}{canManage&&<button onClick={()=>void api(`/tenant/inventory/categories/${c.id}`,{method:"PATCH",body:JSON.stringify({isActive:!c.isActive})}).then(load).catch(e=>setError(e.message))}>{c.isActive?"غیرفعال‌سازی":"فعال‌سازی"}</button>}</article>)}</div></section></div>}
    {busy&&<p className="inventory-loading" role="status">در حال دریافت اطلاعات…</p>}
  </section>;
}

function StockTable({rows,onAdjust}:{rows:Stock[];onAdjust?:(id:string)=>void}){return <div className="inventory-table-scroll" tabIndex={0}><table className="inventory-table"><thead><tr><th>کالا</th><th>دسته</th><th>محل</th><th>موجودی</th><th>آخرین تغییر</th><th /></tr></thead><tbody>{rows.map(r=><tr key={`${r.itemId}:${r.locationId}`}><td><strong>{r.name}</strong><small>{r.sku||unitNames[r.baseUnit]}</small></td><td>{r.categoryName||"—"}</td><td>{r.locationName}</td><td className={Number(r.quantityBase)<0?"negative-stock":""}><strong>{decimal(r.quantityBase)}</strong> {unitNames[r.baseUnit]}{Number(r.quantityBase)<0&&<small>موجودی منفی</small>}{r.averageUnitCostToman&&<small>میانگین: {decimal(r.averageUnitCostToman)} تومان / {unitNames[r.baseUnit]}</small>}</td><td>{r.lastMovementAt?new Date(r.lastMovementAt).toLocaleDateString("fa-IR"):"بدون حرکت"}</td><td>{r.isActive&&onAdjust&&<button className="inventory-link-button" onClick={()=>onAdjust(`${r.itemId}:${r.locationId}`)}>اصلاح</button>}</td></tr>)}{!rows.length&&<tr><td colSpan={6}>کالایی مطابق این فیلتر پیدا نشد.</td></tr>}</tbody></table></div>;}
function AdjustmentDialog({row,close,save}:{row:Stock;close:()=>void;save:(e:FormEvent<HTMLFormElement>,row:Stock)=>void}){return <div className="inventory-dialog-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><form className="inventory-dialog" onSubmit={e=>save(e,row)}><button type="button" className="inventory-dialog-close" onClick={close} aria-label="بستن">×</button><h2>اصلاح موجودی {row.name}</h2><p>مقدار را با علامت مثبت یا منفی و به واحد {unitNames[row.baseUnit]} وارد کنید.</p><label>مقدار تغییر<input name="quantity" required inputMode="decimal" placeholder="مثبت برای افزایش، منفی برای کاهش" pattern="-?[0-9]+(\.[0-9]{1,6})?"/></label><label>دلیل اصلاح<select name="reason" required><option value="اصلاح موجودی">اصلاح موجودی</option><option value="رسید ثبت‌نشده">رسید ثبت‌نشده</option><option value="کسری یا مفقودی">کسری یا مفقودی</option><option value="آسیب‌دیدگی">آسیب‌دیدگی</option><option value="سایر">سایر</option></select></label><div className="inventory-actions"><button type="button" className="inventory-secondary" onClick={close}>انصراف</button><button className="inventory-primary">ثبت اصلاح</button></div></form></div>;}
function ItemEditDialog({item,categories,close,save}:{item:Item;categories:Category[];close:()=>void;save:(e:FormEvent<HTMLFormElement>,item:Item)=>void}){return <div className="inventory-dialog-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><form className="inventory-dialog" onSubmit={e=>save(e,item)}><button type="button" className="inventory-dialog-close" onClick={close} aria-label="بستن">×</button><h2>ویرایش کالای {item.name}</h2><label>نام<input name="name" required maxLength={140} defaultValue={item.name}/></label><label>کد داخلی<input name="sku" maxLength={80} defaultValue={item.sku??""}/></label><label>دسته‌بندی<select name="categoryId" defaultValue={item.categoryId??""}><option value="">بدون دسته‌بندی</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>توضیحات<input name="description" maxLength={500} defaultValue={item.description??""}/></label><div className="inventory-actions"><button type="button" className="inventory-secondary" onClick={close}>انصراف</button><button className="inventory-primary">ذخیره</button></div></form></div>;}
function MovementTable({data}:{data:Page<Movement>}){return <div className="inventory-table-scroll" tabIndex={0}><table className="inventory-table"><thead><tr><th>زمان</th><th>کالا</th><th>محل</th><th>نوع تغییر</th><th>مقدار</th><th>دلیل</th></tr></thead><tbody>{data.items.map(m=><tr key={m.id}><td>{new Date(m.createdAt).toLocaleString("fa-IR")}</td><td>{m.itemName}</td><td>{m.locationName}</td><td>{movementNames[m.type]??m.type}</td><td className={m.quantityBase.startsWith("-")?"negative-stock":""}>{decimal(m.quantityBase)}{m.type==="PURCHASE_RECEIPT"&&m.totalCostToman&&<small>{decimal(m.totalCostToman)} تومان</small>}</td><td>{m.reason||"—"}</td></tr>)}{!data.items.length&&<tr><td colSpan={6}>هنوز تغییری ثبت نشده است.</td></tr>}</tbody></table></div>;}
