"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAdminSession } from "../admin-session";
import { MediaEditor } from "./media-editor";
type OpeningHour = { dayOfWeek: number; isClosed: boolean; opensAt: string | null; closesAt: string | null };
type Site = { name: string; branchName: string; content: { heroTitle: string; heroSubtitle: string | null; aboutTitle: string | null; aboutBody: string | null; announcementText: string | null }; theme: { primaryColor: string; secondaryColor: string; accentColor: string; headingFont: string; bodyFont: string; radiusPreset: "SOFT" | "ROUNDED" | "EDITORIAL" }; contact: { phone: string | null; address: string | null; latitude: string | null; longitude: string | null; instagramUrl: string | null }; openingHours: OpeningHour[] };
type FormState = { name: string; branchName: string; heroTitle: string; heroSubtitle: string; aboutTitle: string; aboutBody: string; announcementText: string; instagramUrl: string; primaryColor: string; secondaryColor: string; accentColor: string; headingFont: string; bodyFont: string; radiusPreset: Site["theme"]["radiusPreset"]; contactPhone: string; address: string; latitude: string; longitude: string; openingHours: OpeningHour[] };
const days = ["یکشنبه", "دوشنبه", "سه‌شنبه", "چهارشنبه", "پنجشنبه", "جمعه", "شنبه"];
const defaultHours = days.map((_, dayOfWeek) => ({ dayOfWeek, isClosed: false, opensAt: "08:00", closesAt: "23:00" }));
function toForm(site: Site): FormState { const existing = new Map(site.openingHours.map((item) => [item.dayOfWeek, item])); return { name: site.name, branchName: site.branchName, heroTitle: site.content.heroTitle, heroSubtitle: site.content.heroSubtitle ?? "", aboutTitle: site.content.aboutTitle ?? "", aboutBody: site.content.aboutBody ?? "", announcementText: site.content.announcementText ?? "", instagramUrl: site.contact.instagramUrl ?? "", primaryColor: site.theme.primaryColor, secondaryColor: site.theme.secondaryColor, accentColor: site.theme.accentColor, headingFont: site.theme.headingFont, bodyFont: site.theme.bodyFont, radiusPreset: site.theme.radiusPreset, contactPhone: site.contact.phone ?? "", address: site.contact.address ?? "", latitude: site.contact.latitude ?? "", longitude: site.contact.longitude ?? "", openingHours: defaultHours.map((fallback) => ({ ...(existing.get(fallback.dayOfWeek) ?? fallback) })) }; }
function nullable(value: string) { return value.trim() || null; }
export function SiteEditor() {
  const { access, api } = useAdminSession();
  return <SiteSettingsEditor api={api} permitted={access.permissions.includes("site.manage")} />;
}
export type SiteApi = <T>(path: string, init?: RequestInit) => Promise<T>;
export function SiteSettingsEditor({ api, permitted = true, basePath = "/tenant", platform = false, onSaved }: { api: SiteApi; permitted?: boolean; basePath?: string; platform?: boolean; onSaved?: () => void }) {
  const [form, setForm] = useState<FormState | null>(null), [busy, setBusy] = useState(true), [dirty, setDirty] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const load = useCallback(async () => { const result = await api<Site>(`${basePath}/site`); setForm(toForm(result)); setDirty(false); }, [api, basePath]);
  useEffect(() => { if (!permitted) return; load().catch((reason: Error) => setError(reason.message)).finally(() => setBusy(false)); }, [load, permitted]);
  if (!permitted) return <section className="admin-section-state"><p className="eyebrow">دسترسی محدود</p><h1>وب‌سایت</h1><p>نقش شما اجازه ویرایش وب‌سایت را ندارد.</p></section>;
  if (busy && !form) return <section className="admin-section-state" aria-live="polite"><span className="admin-spinner" /><h1>در حال بارگذاری وب‌سایت…</h1></section>;
  if (!form) return <section className="admin-section-state error-state"><h1>وب‌سایت بارگذاری نشد</h1><p role="alert">{error}</p><button onClick={() => location.reload()}>تلاش دوباره</button></section>;
  const change = <K extends keyof FormState>(key: K, value: FormState[K]) => { setForm((current) => current ? { ...current, [key]: value } : current); setDirty(true); setNotice(""); };
  function changeHour(dayOfWeek: number, patch: Partial<OpeningHour>) { setForm((current) => current ? { ...current, openingHours: current.openingHours.map((hour) => hour.dayOfWeek === dayOfWeek ? { ...hour, ...patch } : hour) } : current); setDirty(true); setNotice(""); }
  async function save(event: FormEvent) { event.preventDefault(); if (!form) return; const current = form; setBusy(true); setError(""); setNotice(""); try { const payload = { ...current, heroSubtitle: nullable(current.heroSubtitle), aboutTitle: nullable(current.aboutTitle), aboutBody: nullable(current.aboutBody), announcementText: nullable(current.announcementText), instagramUrl: nullable(current.instagramUrl), contactPhone: nullable(current.contactPhone), address: nullable(current.address), latitude: nullable(current.latitude), longitude: nullable(current.longitude), openingHours: current.openingHours.map((hour) => hour.isClosed ? { dayOfWeek: hour.dayOfWeek, isClosed: true } : { dayOfWeek: hour.dayOfWeek, isClosed: false, opensAt: hour.opensAt, closesAt: hour.closesAt }) }; const result = await api<Site>(`${basePath}/site`, { method: "PUT", body: JSON.stringify(payload) }); setForm(toForm(result)); setDirty(false); setNotice("اطلاعات کافه ذخیره شد؛ نمایش عمومی تابع وضعیت اشتراک است."); onSaved?.(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  return <section className="admin-editor-shell"><header className="admin-page-heading"><div><p className="eyebrow">هویت و محتوای کافه</p>{platform ? <h2>اطلاعات و ظاهر کافه</h2> : <h1>وب‌سایت</h1>}<p>محتوا، رنگ‌ها، اطلاعات تماس و ساعت‌های کاری سایت عمومی را مدیریت کنید.</p></div>{!platform && <a className="admin-preview-link" href="/" target="_blank" rel="noreferrer">مشاهده سایت ↗</a>}</header>{error && <p className="admin-message error" role="alert">{error}</p>}{notice && <p className="admin-message success" role="status">{notice}</p>}<form className="site-editor-form" onSubmit={save}>
    <fieldset disabled={busy}><legend>نام کافه و شعبه</legend><div className="editor-grid"><label>نام کافه<input required maxLength={160} value={form.name} onChange={e => change("name", e.target.value)} /></label><label>نام شعبه<input required maxLength={160} value={form.branchName} onChange={e => change("branchName", e.target.value)} /></label></div></fieldset>
    <fieldset disabled={busy}><legend>محتوای صفحه اصلی</legend><div className="editor-grid"><label className="wide">تیتر اصلی<input maxLength={140} value={form.heroTitle} onChange={(e) => change("heroTitle", e.target.value)} required /></label><label className="wide">زیرتیتر<textarea maxLength={320} value={form.heroSubtitle} onChange={(e) => change("heroSubtitle", e.target.value)} /></label><label>عنوان داستان<input maxLength={140} value={form.aboutTitle} onChange={(e) => change("aboutTitle", e.target.value)} /></label><label>نوار اعلان<input maxLength={180} value={form.announcementText} onChange={(e) => change("announcementText", e.target.value)} /></label><label className="wide">متن داستان<textarea maxLength={4000} rows={5} value={form.aboutBody} onChange={(e) => change("aboutBody", e.target.value)} /></label></div></fieldset>
    <MediaEditor api={api} basePath={basePath} privatePreview={platform} />
    <fieldset disabled={busy}><legend>ظاهر کنترل‌شده</legend><p className="fieldset-help">رنگ‌ها و گزینه‌های تأییدشده، خوانایی سایت را حفظ می‌کنند.</p><div className="theme-editor"><div className="editor-grid"><label>رنگ اصلی<span className="color-input"><input type="color" value={form.primaryColor} onChange={(e) => change("primaryColor", e.target.value)} /><code>{form.primaryColor.toUpperCase()}</code></span></label><label>رنگ زمینه<span className="color-input"><input type="color" value={form.secondaryColor} onChange={(e) => change("secondaryColor", e.target.value)} /><code>{form.secondaryColor.toUpperCase()}</code></span></label><label>رنگ تأکیدی<span className="color-input"><input type="color" value={form.accentColor} onChange={(e) => change("accentColor", e.target.value)} /><code>{form.accentColor.toUpperCase()}</code></span></label><label>فرم گوشه‌ها<select value={form.radiusPreset} onChange={(e) => change("radiusPreset", e.target.value as FormState["radiusPreset"])}><option value="SOFT">نرم</option><option value="ROUNDED">گرد</option><option value="EDITORIAL">ادیتوریال</option></select></label><label>فونت تیتر<select value={form.headingFont} onChange={(e) => change("headingFont", e.target.value)}><option>Estedad</option><option>Vazirmatn</option><option>Peyda</option></select></label><label>فونت متن<select value={form.bodyFont} onChange={(e) => change("bodyFont", e.target.value)}><option>Vazirmatn</option><option>Estedad</option></select></label></div><div className={`theme-preview radius-${form.radiusPreset.toLowerCase()}`} style={{ background: form.secondaryColor, color: form.primaryColor }}><small>پیش‌نمایش رنگ</small><strong>{form.heroTitle || "نام کافه شما"}</strong><span style={{ background: form.accentColor }}>مشاهده منو</span></div></div></fieldset>
    <fieldset disabled={busy}><legend>تماس و نشانی</legend><div className="editor-grid"><label>تلفن کافه<input dir="ltr" maxLength={32} value={form.contactPhone} onChange={(e) => change("contactPhone", e.target.value)} /></label><label>اینستاگرام<input dir="ltr" type="url" placeholder="https://instagram.com/..." value={form.instagramUrl} onChange={(e) => change("instagramUrl", e.target.value)} /></label><label className="wide">نشانی<textarea maxLength={1000} value={form.address} onChange={(e) => change("address", e.target.value)} /></label><label>عرض جغرافیایی<input dir="ltr" inputMode="decimal" placeholder="35.6892" value={form.latitude} onChange={(e) => change("latitude", e.target.value)} /></label><label>طول جغرافیایی<input dir="ltr" inputMode="decimal" placeholder="51.3890" value={form.longitude} onChange={(e) => change("longitude", e.target.value)} /></label></div></fieldset>
    <fieldset disabled={busy}><legend>ساعت‌های کاری</legend><div className="hours-editor">{form.openingHours.map((hour) => <div className="hour-row" key={hour.dayOfWeek}><strong>{days[hour.dayOfWeek]}</strong><label className="compact-toggle"><input type="checkbox" checked={hour.isClosed} onChange={(e) => changeHour(hour.dayOfWeek, { isClosed: e.target.checked })} />تعطیل</label><label>باز شدن<input type="time" disabled={hour.isClosed} value={hour.opensAt ?? "08:00"} onChange={(e) => changeHour(hour.dayOfWeek, { opensAt: e.target.value })} required={!hour.isClosed} /></label><label>بسته شدن<input type="time" disabled={hour.isClosed} value={hour.closesAt ?? "23:00"} onChange={(e) => changeHour(hour.dayOfWeek, { closesAt: e.target.value })} required={!hour.isClosed} /></label></div>)}</div></fieldset>
    <div className="editor-savebar"><span>{dirty ? "تغییرات ذخیره‌نشده دارید." : "همه تغییرات ذخیره شده‌اند."}</span><button disabled={busy || !dirty}>{busy ? "در حال انتشار…" : "ذخیره و انتشار"}</button></div>
  </form></section>;
}
